-- AlterTable
ALTER TABLE "Task"
  ADD COLUMN IF NOT EXISTS "sponsorBudgetCurrency" TEXT,
  ADD COLUMN IF NOT EXISTS "sponsorBudgetAmount" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sponsorBudgetSpent" DOUBLE PRECISION NOT NULL DEFAULT 0;
